# Generated by Django 5.2.10 on 2026-01-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GigradarProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.CharField(db_index=True, help_text='ID proposal з Gigradar', max_length=255, unique=True)),
                ('opportunity_id', models.CharField(db_index=True, help_text='ID opportunity', max_length=255)),
                ('job_id', models.CharField(blank=True, db_index=True, help_text='ID job з Upwork', max_length=255, null=True)),
                ('status', models.CharField(blank=True, help_text='Статус proposal', max_length=100, null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Дата відправки proposal', null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Запланована дата відправки', null=True)),
                ('created_at', models.DateTimeField(blank=True, help_text='Дата створення в Gigradar', null=True)),
                ('has_error', models.BooleanField(default=False, help_text='Чи є помилка при відправці')),
                ('error_code', models.CharField(blank=True, help_text='Код помилки', max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Повідомлення про помилку', null=True)),
                ('scanner_id', models.CharField(blank=True, help_text='ID scanner', max_length=255, null=True)),
                ('scanner_name', models.CharField(blank=True, help_text='Назва scanner', max_length=255, null=True)),
                ('team_id', models.CharField(blank=True, help_text='ID team', max_length=255, null=True)),
                ('team_name', models.CharField(blank=True, help_text='Назва team', max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, help_text='Назва job', max_length=500, null=True)),
                ('job_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Бюджет job', max_digits=10, null=True)),
                ('job_type', models.CharField(blank=True, help_text='Тип job (hourly/fixed)', max_length=50, null=True)),
                ('client_email', models.EmailField(blank=True, db_index=True, help_text='Email клієнта', max_length=254, null=True)),
                ('client_name', models.CharField(blank=True, help_text="Ім'я клієнта", max_length=255, null=True)),
                ('client_company', models.CharField(blank=True, help_text='Компанія клієнта', max_length=255, null=True)),
                ('hubspot_contact_id', models.CharField(blank=True, db_index=True, help_text='ID контакту в HubSpot', max_length=255, null=True)),
                ('hubspot_deal_id', models.CharField(blank=True, db_index=True, help_text='ID deal в HubSpot', max_length=255, null=True)),
                ('raw_data', models.JSONField(default=dict, help_text='Повні дані з webhook у форматі JSON')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Дата створення запису в БД')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Дата останнього оновлення')),
            ],
            options={
                'verbose_name': 'Gigradar Proposal',
                'verbose_name_plural': 'Gigradar Proposals',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['proposal_id'], name='integration_proposa_caefd8_idx'), models.Index(fields=['opportunity_id'], name='integration_opportu_1e573d_idx'), models.Index(fields=['job_id'], name='integration_job_id_b59f03_idx'), models.Index(fields=['client_email'], name='integration_client__8643b0_idx'), models.Index(fields=['-created'], name='integration_created_91fb42_idx'), models.Index(fields=['status'], name='integration_status_0f387b_idx')],
            },
        ),
    ]
